version = 0.1
[default.deploy.parameters]
stack_name = "TWKnowledgeManager"
resolve_s3 = true
s3_prefix = "TWKnowledgeManager"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
